---
    - name: Install php
      yum:
        name: php
        state: installed

    - name: copy php
      copy:
        src: date.php
        dest: /var/www/html/date.php
      notify:
        - Restart Httpd
 
    - name: Template
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html 

    - name: Template
      template:
        src: httpd.j2
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - Restart Httpd
          
...
